window.FORTUNES = [
  "PREDICTION: A classy, top shelf, total legend will be coming into your therapy clinic. Mostly on Mondays at 3pm.",
  "If you're having a bad day, just remember: At least you're still SIGNIFICANTLY younger than some of your clients.",
  "Amelia! You beautiful, rule-breaking moth!",
  "Where do you feel that in your body? Go with that.",
  "Nup. Not happening.",
  "Fruit and nut chocolate is a terrible choice.",
  "You're doing your best. Which is fucking embarrassing.",
  "Perhaps it's time to buy a top sheet. Just a thought.",
  "I'm not a social butterfly but if you want a disassociating moth, hit me up.",
  "Ya mum.",
  "Wait. Maybe therapy IS the problem?",
  "Treat yo self!",
  "Fameli, you beautiful tropical fish! You're smart as a whip and cool under pressure.",
  "You need therapy.",
  "MT, you genius! Your brain is almost as perfect as your face.",
  "All your hard work will soon pay off. Or maybe it won't. I don't know.",
  "You're beautiful and you're organised!",
  "The fortune you seek is in another cookie.",
  "To Do: Avoid the morbs.",
  "This cookie is never gonna give you up, never gonna let you down.",
  "Carve your name on hearts, not marble. I don't know what this means but it's triggering my avoidant attachment.",
  "This too shall pass...  OK, but like, when?",
  "Right now, you are the most beautiful, glowing sun-goddess ever.",
  "Now, every time I'm at the beach I think about how you're somehow always eating sand and feel concerned.",
  "RAT BASTARD.",
  "Who allowed you to be this beautiful?",
  "Only listen to this fortune cookie. Disregard all other fortune cookies.",
  "Love yourself you piece of shit.",
  "I cannot help you, for I am just a cookie.",
  "Less where do you feel that in your body and more tattoos and Aperol Spritz's please.",
  "If a turtle doesn't have a shell, is it naked or homeless?",
  "Ignore previous cookie.",
  "Dreams are the touchstones of our character (I have no idea what this means).",
  "Good news will come to you by mail. And ongoing attempted cancellations will continue to arrive by email. And maybe text.",
  "Jesus, take the wheel already.",
  "Fameli, you tricky bastard. Go get 'em.",
  "Remember: Old people don't mean to have fragile bones.",
  "Your quiet support means the world to me. As well as your tacit endorsement of all my behaviours.",
  "Maybe it's time to scope the edges? (I still have no idea what this means).",
  "There's nothing we can't do if we work hard, never sleep and shirk all other responsibilities in our lives.",
  "Love fades. Things are forever.",
  "You're doing great sweetie!",
  "I love your disordered thinking.",
  "This one's broken.",
  "You're a national treasure.",
  "Keys? Check. Wallet? Check. Airtags that have the complete wrong names? Check.",
  "Your mind is your greatest treasure (Well, I mean.. yours might be. Mine's a liability).",
  "You have the time management skills of a cucumber.",
  "You're a freckle faced fart from Kmart.",
  "Talent! Beauty! Class!",
  "Granola 4 Eva.",
  "It's a no from me.",
  "Remember: Sometimes you just gotta throw some shit to the wind and see what sticks.",
  "I would rather bleed out than sit here and talk about my feelings for 10 minutes.",
  "You're welcome, you beady-eyed bastard.",
  "What... and I mean this respectfully... the fuck?!",
  "Got memes?",
  "High five, still alive.",
  "Just between us, you got that big tism energy.",
  "You seem a little dysfunctional.",
  "Get in the bin.",
  "This fortune only exists so there wouldn't be an odd number of fortunes."
];
