window.FORTUNES = [
  "PREDICTION: A classy, top shelf, total legend will be coming into your therapy clinic. Mostly on Mondays. At 3pm. 315pm at the latest.",
  "If you're having a bad day, just remember: At least you're still SIGNIFICANTLY younger than some of your clients.",
  "Amelia! You beautiful, rule-breaking moth!",
  "Where do you feel that in your body? gO wItH tHaT.",
  "You are a child with the bubonic plague! It's time to don your night garments and read by candlelight. Not hit up The Frat for cheap pizzas!",
  "Fruit and nut chocolate is a terrible choice.",
  "You're doing your best. Which is fucking embarrassing.",
  "Perhaps it's time to buy a top sheet. Just a thought.",
  "Ya mum.",
  "Wait. Maybe therapy IS the problem?",
  "Treat yo self!",
  "Fameli, you beautiful tropical fish! You're smart as a whip and cool under pressure.",
  "Good try Fameli, good try.",
  "You continue to be the little bull to the fine china that is my life.",
  "The crazy bird lady with the trolley is starting to look like a really good option right about now.",
  "YOU HAVE D.I.D! MERRY CHRISTMAS!",
  "You need therapy.",
  "MT, you genius! Your brain is almost as perfect as your face.",
  "All your hard work will soon pay off. Or maybe it won't. I don't know.",
  "You're beautiful and you're (somewhat) organised!",
  "The fortune you seek is in another cookie.",
  "To Do: Avoid the morbs.",
  "This cookie is never gonna give you up, never gonna let you down.",
  "Carve your name on hearts, not marble. I don't know what this means but it's triggering my avoidant attachment.",
  "This too shall pass...  OK, but like, when?",
  "Right now, you are the most beautiful, glowing sun-goddess ever.",
  "Now, every time I'm at the beach I think about how you're somehow always eating sand and feel concerned.",
  "RAT BASTARD.",
  "Who allowed you to be this beautiful?",
  "Only listen to this fortune cookie. Disregard all other fortune cookies.",
  "Love yourself you piece of shit.",
  "Just between us, I'm not sure if you completely understand what a check in is. Sometimes yours tend to feel more like bombs dropping on a bad day in Bosnia. Good try though.",
  "Thank you for being the little lighthouse guiding this sinking ship to shore. Or somewhere near shore, as I can tell you have a terrible sense of direction.",
  "You should probably stop flirting with your colleagues and/or students. Just my 2c.",
  "If all else fails you can always become a staff member at Spotlight. I've seen you get cranky - you'll fit right in.",
  "I cannot help you, for I am just a cookie.",
  "Less where do you feel that in your body and more tattoos and Aperol Spritz's please.",
  "Question that's been bothering me lately - If a turtle doesn't have a shell, is it naked or homeless?",
  "Ignore previous cookie.",
  "Dreams are the touchstones of our character (I have no idea what this means).",
  "Good news will come to you by mail. And ongoing attempted cancellations will continue to arrive by email. And maybe text.",
  "Jesus, take the wheel already.",
  "Fameli, you tricky bastard. Go get 'em.",
  "Remember: Old people don't mean to have fragile bones.",
  "Some days you just gotta pretend to be an axolotl in the pool and that's OK, you know?",
  "Maybe it's time to scope the edges? (I still have no idea what this means).",
  "Just remember: There's nothing we can't do if we work hard, never sleep and shirk all other responsibilities in our lives.",
  "Love fades. Things are forever.",
  "You're doing great sweetie!",
  "I love your (disordered) thinking.",
  "You're a national treasure.",
  "Keys? Check. Wallet? Check. Airtags that have the complete wrong names? Check.",
  "Your mind is your greatest treasure (Well, I mean.. yours might be. Mine's a liability).",
  "You have the time management skills of a potato.",
  "You're a freckle faced fart from Kmart.",
  "Talent! Beauty! Class!",
  "Granola 4 Eva.",
  "EMDR? It's a no from me.",
  "Remember: Sometimes you just gotta throw some shit to the wind and see what sticks.",
  "Adaptive coping mechanism? Never heard of her!",
  "I would rather bleed out than sit here and talk about my feelings for 10 minutes.",
  "You're welcome, you beady-eyed bastard.",
  "What... and I mean this respectfully... the fuck?!",
  "Chocolate covered sultanas? Immediately no.",
  "Got memes?",
  "High five, still alive.",
  "Just between us, you got that big tism energy.",
  "You seem a little dysfunctional.",
  "Fameli, get in the bin.",
  "This fortune only exists so there wouldn't be an odd number of fortunes.",
  "Started from the bottom. Now we're a little bit below the bottom."
];
