window.FORTUNES = [
  "A beautiful, smart, and loving person will be coming into your life.",
  "Treat yo self!",
  "A faithful friend is a strong defense.",
  "I see money in your future... it's not yours though.",
  "A feather in the hand is better than a bird in the air.",
  "A fresh start will put you on your way.",
  "A friend asks only for your time not your money.",
  "A friend is a present you give yourself.",
  "A golden egg of opportunity falls into your lap this month.",
  "A good time to finish up old tasks.",
  "A lifetime of happiness lies ahead of you.",
  "A light heart carries you through all the hard times.",
  "You genius! Your brain is almost as perfect as your face.",
  "You're beautiful and you're organised!",
  "All your hard work will soon pay off.",
  "An unexpected windfall will appear soon.",
  "Believe it can be done.",
  "This cookie is never gonna give you up, never gonna let you down.",
  "Carve your name on hearts, not marble.",
  "Right now, you are the most beautiful, glowing sun-goddess ever.",
  "Change can hurt, but it leads a path to something better.",
  "No snowflake in an avalanche ever feels responsible",
  "I cannot help you, for I am just a cookie.",
  "Perhaps you've been focusing too much on spending.",
  "Perhaps you've been focusing too much on saving.",
  "Hey, good lookin'!",
  "Do what you love, the rest will follow.",
  "Dreams are the touchstones of our character.",
  "Every day is a new opportunity.",
  "Fortune favors the bold.",
  "From now on your kindness will lead you to success.",
  "Good news will come to you by mail.",
  "Happiness begins with facing life with a smile and a wink.",
  "If you continually give, you will continually have.",
  "It is now, and in this world, that we must live.",
  "Luck sometimes visits a fool, but it never sits down with him.",
  "Now is the time to try something new.",
  "Say yes to new adventures.",
  "Serendipity will surprise you today.",
  "Soon life will become more interesting.",
  "The early bird gets the worm, but the second mouse gets the cheese.",
  "The greatest risk is not taking one.",
  "The harder you work, the luckier you get.",
  "The world is your oyster.",
  "There are no shortcuts to any place worth going.",
  "Today is a lucky day for those who remain cheerful and optimistic.",
  "Trust your intuition—it is your friend.",
  "Unexpected wealth will be yours.",
  "Your ability for accomplishment will follow with success.",
  "Your dreams are never silly; depend on them to guide you.",
  "Your mind is your greatest treasure.",
  "Your passions determine your path.",
  "If you can befriend yourself, you will never be lonely.",
  "Don't let yesterday take up too much of today.",
  "A balanced diet is a cookie in each hand."
];